"use client";

import { SuppressAppFeedback } from "@/app/(app)/_components.tsx/app-feedback-visibility";
import { ROUTES } from "@/app/constants";
import { PremiumFeatureNotice } from "@/components/premium-feature-notice";
import { LeftoverIngredientsPicker } from "@/components/recipes/leftover-ingredients-picker";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ANALYTICS_EVENTS } from "@/lib/analytics/events";
import { trackEvent } from "@/lib/analytics/posthog-client";
import { pickPreferredMealPlanIdFromSummaries } from "@/lib/meal-plan-preference";
import { navigateBackOr } from "@/lib/navigation";
import { cn, startOfLocalDayMs } from "@/lib/utils";
import { api } from "convex/_generated/api";
import { Id } from "convex/_generated/dataModel";
import {
  BETA_FREE_INCLUDES_PREMIUM_FEATURES,
  MAX_DAYS_IN_MEAL_PLAN,
  MEAL_PLAN_ERRORS,
  QUICK_MEALS_MIN_MINUTES,
  TARGET_SERVINGS_MAX,
  TARGET_SERVINGS_MIN,
} from "convex/lib/constants";
import { useMutation, useQuery } from "convex/react";
import type { FunctionReturnType } from "convex/server";
import {
  ArrowLeft,
  ArrowRight,
  CalendarPlus,
  Check,
  CheckCircle2,
  Clock3,
  Home,
  Loader2,
  MoreVertical,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Trash2,
  UserMinus,
  UserRoundCheck,
  Users,
} from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import type { ReactNode } from "react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { EmptySlot } from "./empty-slot";
import { MealPlanCard } from "./meal-plan-card";
import { MealPlanDayView } from "./meal-plan-day-view";
import { MealPlanRecipePickerModal } from "./meal-plan-recipe-picker-modal";

const MEAL_PLAN_LAST_VIEWED_STORAGE_KEY = "foodedo_meal_plan_last_viewed_id";
const MEAL_PLAN_GENERATION_FALLBACK_NOTICE_SESSION_KEY =
  "foodedo_meal_plan_generation_fallback_notice";

type GenerationFallbackStage = "recency_relaxed" | "non_allergy_relaxed";

function generationFallbackMessage(stage: GenerationFallbackStage): {
  toast: string;
  banner: string;
} {
  if (stage === "recency_relaxed") {
    return {
      toast:
        "We built your plan by relaxing recent-meal repetition for this run.",
      banner:
        "This plan was generated by relaxing recent-meal repetition rules after your first attempt returned no eligible results.",
    };
  }
  return {
    toast:
      "We built your plan by relaxing non-allergy household preferences for this run.",
    banner:
      "This plan was generated by relaxing non-allergy household preferences after stricter attempts returned no eligible results. Allergy rules remained enforced.",
  };
}

/** Short codes for PostHog — never send raw exception text from user mutations. */
function mealPlanGenerateFailureReason(e: unknown): string {
  const msg = e instanceof Error ? e.message : String(e);
  if (/no recipes available/i.test(msg)) return "empty_recipe_pool";
  if (/timeout|timed out|network|fetch failed|failed to fetch/i.test(msg)) {
    return "network";
  }
  if (/convex|mutation|unauthorized|forbidden|not found/i.test(msg)) {
    return "backend_error";
  }
  if (/invalid|validation|must be|required/i.test(msg)) {
    return "validation_error";
  }
  return "unknown_error";
}

function mealPlanErrorMessage(e: unknown): string {
  const msg = e instanceof Error ? e.message : String(e);
  if (msg.includes(MEAL_PLAN_ERRORS.PREMIUM_REQUIRED_MULTIPLE_MEAL_PLANS)) {
    return "Multiple active meal plans are a premium feature. Upgrade to create another plan.";
  }
  if (msg.includes(MEAL_PLAN_ERRORS.PREMIUM_REQUIRED_LEFTOVER_INGREDIENTS)) {
    return "Leftover-ingredient management is a premium feature. Upgrade to enable it.";
  }
  if (
    msg.includes(MEAL_PLAN_ERRORS.PREMIUM_REQUIRED_ADVANCED_MEAL_PLAN_CONTROLS)
  ) {
    return "Custom start dates and day lengths are premium controls.";
  }
  if (msg.includes(MEAL_PLAN_ERRORS.PREMIUM_REQUIRED_HOUSEHOLD_PREFERENCES)) {
    return "Household preference filtering is a premium feature.";
  }
  if (msg.includes(MEAL_PLAN_ERRORS.HOUSEHOLD_PREFERENCES_NO_RECIPES)) {
    return "No recipes match the selected member preferences. Try toggling fewer members or loosening restrictions.";
  }
  if (msg.includes(MEAL_PLAN_ERRORS.PREMIUM_REQUIRED_QUICK_MEALS)) {
    return "Quick meal targeting is a premium feature.";
  }
  if (msg.includes(MEAL_PLAN_ERRORS.QUICK_MEALS_NO_RECIPES)) {
    return "Not enough recipes match that quick-meals preset. Try Automatic or a lighter preset.";
  }
  if (msg.includes("No eligible recipes matched your current constraints")) {
    return "We couldn't find enough eligible meals with your current filters. Try loosening member preferences, quick-meal settings, or recency constraints.";
  }
  return msg;
}
const MEAL_PLAN_EMPTY_VIEWED_SESSION_KEY =
  "foodedo_onboarding_meal_plan_empty_viewed";

type CurrentPlan = NonNullable<
  FunctionReturnType<typeof api.mealPlans.getMealPlan>
>;

function formatPlanRangeShort(start: number | undefined, end: number): string {
  const fmt = (ms: number) =>
    new Date(ms).toLocaleDateString(undefined, {
      day: "numeric",
      month: "short",
      timeZone: "UTC",
    });
  if (start !== undefined) return `${fmt(start)} – ${fmt(end)}`;
  return fmt(end);
}

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

type MealPlanClientProps = {
  planId?: string;
  generationOnly?: boolean;
};

type MealPlanSummary = NonNullable<
  FunctionReturnType<typeof api.mealPlans.getActiveMealPlanSummaries>
>[number];

type QuickMealsPresetId = "automatic" | "light" | "balanced" | "fast_focused";

const QUICK_MEAL_PRESETS: Array<{
  id: QuickMealsPresetId;
  title: string;
  description: string;
  count?: number;
  maxMinutes?: number;
}> = [
  {
    id: "automatic",
    title: "Automatic",
    description: "Balanced speed for the week",
  },
  {
    id: "light",
    title: "Light",
    description: "At least 2 meals under 45m",
    count: 2,
    maxMinutes: 45,
  },
  {
    id: "balanced",
    title: "Balanced",
    description: "At least 3 meals under 40m",
    count: 3,
    maxMinutes: 40,
  },
  {
    id: "fast_focused",
    title: "Fast-focused",
    description: "At least 4 meals under 35m",
    count: 4,
    maxMinutes: 35,
  },
];

/** Shared header row for premium meal-plan generator sections (icon + title + Pro badge). */
function MealPlanProSectionHeader({
  icon,
  title,
}: {
  icon: ReactNode;
  title: string;
}) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      {icon}
      <h2 className="text-base font-semibold text-foreground">{title}</h2>
      <Badge
        variant="secondary"
        className="text-[10px] font-semibold uppercase"
      >
        Pro
      </Badge>
    </div>
  );
}

/** Maps quick-meals preset to mutation fields; clamps count to plan length. */
function resolveQuickMealsPayloadFields(
  presetId: QuickMealsPresetId,
  selectedDayCount: number,
): { quickMealsCount: number; quickMealsMaxMinutes: number } | null {
  if (presetId === "automatic") return null;
  const preset = QUICK_MEAL_PRESETS.find((p) => p.id === presetId);
  const count = preset?.count;
  const maxMinutes = preset?.maxMinutes;
  if (count == null || maxMinutes == null) return null;
  return {
    quickMealsCount: Math.min(count, selectedDayCount),
    quickMealsMaxMinutes: maxMinutes,
  };
}

function useMealPlanRoutingState(args: {
  generationOnly: boolean;
  planId?: string;
  planParam: string | null;
  planSummaries: MealPlanSummary[] | undefined;
  localDayStartMs: number;
  router: ReturnType<typeof useRouter>;
}) {
  const resolvedPlanId = useMemo(() => {
    if (args.generationOnly) return null;
    if (args.planParam) return args.planParam as Id<"mealPlans">;
    if (args.planSummaries === undefined) return undefined;
    if (args.planSummaries.length === 0) return null;

    const validIds = new Set(args.planSummaries.map((s) => s._id));
    if (typeof window !== "undefined") {
      const last = sessionStorage.getItem(MEAL_PLAN_LAST_VIEWED_STORAGE_KEY);
      if (last && validIds.has(last as Id<"mealPlans">)) {
        return last as Id<"mealPlans">;
      }
    }
    return pickPreferredMealPlanIdFromSummaries(
      args.planSummaries,
      args.localDayStartMs,
    );
  }, [
    args.generationOnly,
    args.localDayStartMs,
    args.planParam,
    args.planSummaries,
  ]);

  useEffect(() => {
    if (args.generationOnly) return;
    if (args.planId) {
      if (resolvedPlanId && typeof window !== "undefined") {
        sessionStorage.setItem(
          MEAL_PLAN_LAST_VIEWED_STORAGE_KEY,
          resolvedPlanId,
        );
      }
      return;
    }
    if (args.planSummaries === undefined) return;

    if (args.planSummaries.length === 0) {
      return;
    }

    if (resolvedPlanId && args.planParam !== resolvedPlanId) {
      args.router.replace(ROUTES.mealPlanWithId(resolvedPlanId), {
        scroll: false,
      });
    }

    if (resolvedPlanId && typeof window !== "undefined") {
      sessionStorage.setItem(MEAL_PLAN_LAST_VIEWED_STORAGE_KEY, resolvedPlanId);
    }
  }, [
    args.generationOnly,
    args.planId,
    args.planParam,
    args.planSummaries,
    args.router,
    resolvedPlanId,
  ]);

  return resolvedPlanId;
}

type GenerationActionButtonsProps = {
  isGenerating: boolean;
  disabledManual: boolean;
  disabledGenerate: boolean;
  onManual: () => void;
  onGenerate: () => void;
  showUpgradeHint: boolean;
};

function resolveMealPlanEntitlements(args: {
  currentUser: FunctionReturnType<typeof api.users.current> | undefined;
  ownedPlanCountForCreation: number | undefined;
}) {
  const subscriptionTier = args.currentUser?.subscriptionTier ?? "free_user";
  const hasPremiumMealPlanAccess =
    subscriptionTier === "pro_user" ||
    (subscriptionTier === "free_user" && BETA_FREE_INCLUDES_PREMIUM_FEATURES);
  const entitlementsReady =
    args.currentUser !== undefined &&
    args.ownedPlanCountForCreation !== undefined;
  const canUseMealPlanLeftovers =
    entitlementsReady && args.currentUser != null && hasPremiumMealPlanAccess;
  const hasActivePlan =
    entitlementsReady && (args.ownedPlanCountForCreation ?? 0) > 0;
  const blocksAdditionalPlansOnFreeTier =
    entitlementsReady &&
    args.currentUser != null &&
    hasActivePlan &&
    !hasPremiumMealPlanAccess;
  const canUseAdvancedControls =
    entitlementsReady && args.currentUser != null && hasPremiumMealPlanAccess;

  return {
    entitlementsReady,
    canUseMealPlanLeftovers,
    blocksAdditionalPlansOnFreeTier,
    canUseAdvancedControls,
    controlsLocked: !entitlementsReady || !canUseAdvancedControls,
  };
}

function GenerationActionButtons({
  isGenerating,
  disabledManual,
  disabledGenerate,
  onManual,
  onGenerate,
  showUpgradeHint,
}: GenerationActionButtonsProps) {
  return (
    <>
      <div className="flex w-full max-w-sm mx-auto flex-col gap-2 sm:flex-row sm:justify-center">
        <Button
          size="lg"
          variant="outline"
          className="w-full sm:flex-1"
          onClick={onManual}
          disabled={disabledManual}
        >
          {isGenerating ? (
            <Loader2 className="size-5 mr-2 animate-spin" />
          ) : (
            <CalendarPlus className="size-5 mr-2" />
          )}
          Manual plan
        </Button>
        <Button
          size="lg"
          className="w-full sm:flex-1"
          onClick={onGenerate}
          disabled={disabledGenerate}
        >
          {isGenerating ? (
            <Loader2 className="size-5 mr-2 animate-spin" />
          ) : (
            <Sparkles className="size-5 mr-2" />
          )}
          {isGenerating ? "Generating..." : "Generate My Week"}
          {!isGenerating ? <ArrowRight className="size-5 ml-2" /> : null}
        </Button>
      </div>
      {showUpgradeHint ? (
        <p className="mt-3 max-w-sm text-xs text-muted-foreground">
          Free users can only have one active meal plan at a time. If you want
          to create another meal plan, delete your existing one first, or{" "}
          <Link href={ROUTES.PRICING} className="underline underline-offset-4">
            upgrade your account
          </Link>{" "}
          to enable multiple meal plans.
        </p>
      ) : null}
    </>
  );
}

type GenerationMember = NonNullable<
  FunctionReturnType<typeof api.households.getGenerationMembersWithPreferences>
>[number];

function MemberPreferenceCards({
  members,
  includedMemberIds,
  onToggle,
}: {
  members: GenerationMember[];
  includedMemberIds: Set<Id<"users">>;
  onToggle: (userId: Id<"users">) => void;
}) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
      {members.map((member) => {
        const selected = includedMemberIds.has(member.userId);
        return (
          <label
            key={member.userId}
            className={cn(
              "block rounded-lg border p-3 text-left transition-colors cursor-pointer",
              selected
                ? "border-primary bg-primary/10"
                : "border-border bg-card",
            )}
          >
            <input
              type="checkbox"
              className="sr-only"
              checked={selected}
              onChange={() => onToggle(member.userId)}
              aria-label={`Include ${member.name} preferences`}
            />
            <div className="flex items-center justify-between gap-2">
              <span className="font-medium">{member.name}</span>
              <span
                className={cn(
                  "inline-flex size-4 items-center justify-center rounded border text-[10px]",
                  selected
                    ? "border-primary bg-primary text-primary-foreground"
                    : "border-muted-foreground/40 text-transparent",
                )}
              >
                <Check className="size-3" />
              </span>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">
              {member.allergyCount > 0
                ? `${member.allergyCount} allergy rule${member.allergyCount === 1 ? "" : "s"}`
                : "No allergy rules"}
              {member.excludedProteinCount > 0
                ? ` · ${member.excludedProteinCount} protein exclusion${member.excludedProteinCount === 1 ? "" : "s"}`
                : ""}
            </p>
          </label>
        );
      })}
    </div>
  );
}

function QuickMealsPreferenceCard({
  selectedPresetId,
  onSelectPreset,
  isPremiumEnabled,
  selectedDayCount,
}: {
  selectedPresetId: QuickMealsPresetId;
  onSelectPreset: (presetId: QuickMealsPresetId) => void;
  isPremiumEnabled: boolean;
  selectedDayCount: number;
}) {
  return (
    <Card className="mb-6 border-border/80 bg-muted/20 max-w-2xl mx-auto">
      <CardContent className="p-3 space-y-3">
        <MealPlanProSectionHeader
          icon={<Clock3 className="size-4 shrink-0 text-primary" aria-hidden />}
          title="Quick meals"
        />
        <p className="text-sm text-muted-foreground">
          Pick a pace for faster meals this week. Presets guarantee a minimum;
          the rest of the week is filled as usual.
        </p>
        {!isPremiumEnabled ? (
          <PremiumFeatureNotice
            title="Pro feature"
            description="Quick meal targeting is a Pro feature."
          />
        ) : null}
        <div
          role="radiogroup"
          aria-label="Quick meal preference presets"
          className={cn(
            "grid grid-cols-2 gap-2 sm:grid-cols-3",
            !isPremiumEnabled && "pointer-events-none opacity-60",
          )}
        >
          {QUICK_MEAL_PRESETS.map((preset) => (
            <label
              key={preset.id}
              className={cn(
                "rounded-lg border px-3 py-3 text-left text-sm transition-colors cursor-pointer focus-within:ring-2 focus-within:ring-primary/50 focus-within:ring-offset-2",
                selectedPresetId === preset.id
                  ? "border-primary bg-primary/10 text-foreground"
                  : "border-border bg-card text-muted-foreground",
              )}
            >
              <input
                type="radio"
                name="quick-meals-preset"
                value={preset.id}
                checked={selectedPresetId === preset.id}
                onChange={() => onSelectPreset(preset.id)}
                disabled={!isPremiumEnabled}
                className="peer sr-only"
              />
              <div className="font-medium">{preset.title}</div>
              <div className="mt-1 text-xs">
                {preset.id === "automatic"
                  ? preset.description
                  : (() => {
                      const resolved = resolveQuickMealsPayloadFields(
                        preset.id,
                        selectedDayCount,
                      );
                      if (!resolved) return preset.description;
                      return `At least ${resolved.quickMealsCount} meal${resolved.quickMealsCount === 1 ? "" : "s"} under ${resolved.quickMealsMaxMinutes}m`;
                    })()}
              </div>
            </label>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

export default function MealPlanClient({
  planId,
  generationOnly = false,
}: MealPlanClientProps) {
  const emptyViewedTrackedRef = useRef(false);

  const router = useRouter();
  const searchParams = useSearchParams();
  const planParam = planId ?? searchParams.get("plan");

  const localDayStartMs = startOfLocalDayMs(Date.now());

  const planSummaries = useQuery(api.mealPlans.getActiveMealPlanSummaries, {
    localDayStartMs,
  });
  const ownedPlanCountForCreation = useQuery(
    api.mealPlans.getOwnedUnreplacedPlanCountForCreation,
    { localDayStartMs },
  );

  const resolvedPlanId = useMealPlanRoutingState({
    generationOnly,
    planId,
    planParam,
    planSummaries,
    localDayStartMs,
    router,
  });

  useEffect(() => {
    if (planSummaries === undefined || planSummaries.length > 0) return;
    if (emptyViewedTrackedRef.current) return;
    try {
      if (
        typeof window !== "undefined" &&
        sessionStorage.getItem(MEAL_PLAN_EMPTY_VIEWED_SESSION_KEY)
      ) {
        emptyViewedTrackedRef.current = true;
        return;
      }
      if (typeof window !== "undefined") {
        sessionStorage.setItem(MEAL_PLAN_EMPTY_VIEWED_SESSION_KEY, "1");
      }
      emptyViewedTrackedRef.current = true;
      trackEvent(ANALYTICS_EVENTS.ONBOARDING_MEAL_PLAN_EMPTY_VIEWED, {});
    } catch {
      emptyViewedTrackedRef.current = true;
      trackEvent(ANALYTICS_EVENTS.ONBOARDING_MEAL_PLAN_EMPTY_VIEWED, {});
    }
  }, [planSummaries]);

  const currentPlan = useQuery(
    api.mealPlans.getMealPlan,
    resolvedPlanId !== undefined && resolvedPlanId !== null
      ? { mealPlanId: resolvedPlanId }
      : "skip",
  );
  const poolRecipes = useQuery(api.recipes.getRecipesForWeeklyPlan, {
    limit: 50,
  });
  const households = useQuery(api.households.getUserHouseholds);
  const listsForPlan = useQuery(
    api.shoppingLists.getShoppingListsByMealPlan,
    currentPlan ? { mealPlanId: currentPlan._id } : "skip",
  );
  const currentUser = useQuery(api.users.current);
  const personalChalkboard = useQuery(api.chalkboard.getPersonalChalkboard);
  const householdChalkboards = useQuery(
    api.chalkboard.getAllHouseholdChalkboards,
  );

  const generateWeeklyPlan = useMutation(api.mealPlans.generateWeeklyPlan);
  const createBlankWeeklyPlan = useMutation(
    api.mealPlans.createBlankWeeklyPlan,
  );
  const regenerateWeeklyPlan = useMutation(api.mealPlans.regenerateWeeklyPlan);
  const removeEntry = useMutation(api.mealPlans.removeEntry);
  const updateEntry = useMutation(api.mealPlans.updateEntry);
  const addEntry = useMutation(api.mealPlans.addEntry);
  const deleteMealPlan = useMutation(api.mealPlans.deleteMealPlan);
  const shareMealPlanWithHousehold = useMutation(
    api.mealPlans.shareMealPlanWithHousehold,
  );
  const unshareMealPlan = useMutation(api.mealPlans.unshareMealPlan);
  const createShoppingListFromMealPlan = useMutation(
    api.shoppingLists.createShoppingListFromMealPlan,
  );
  const finaliseMealPlan = useMutation(api.mealPlans.finaliseMealPlan);

  const [selectedChalkboardIds, setSelectedChalkboardIds] = useState<
    Set<Id<"chalkboardItems">>
  >(new Set());
  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [showShareDialog, setShowShareDialog] = useState(false);
  const [shareHouseholdId, setShareHouseholdId] = useState<
    Id<"households"> | ""
  >("");
  const [isSharing, setIsSharing] = useState(false);
  const shareInFlightRef = useRef(false);
  const [showDeletePlanDialog, setShowDeletePlanDialog] = useState(false);
  const [showUnshareConfirmDialog, setShowUnshareConfirmDialog] =
    useState(false);
  const [showFinaliseDialog, setShowFinaliseDialog] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [targetServings, setTargetServings] = useState(1);
  const [hasManualServingOverride, setHasManualServingOverride] =
    useState(false);
  /** When the user has multiple households, we default the picker so generation shares to a household; omitting would leave the new plan private. */
  const [generateWeekHouseholdId, setGenerateWeekHouseholdId] = useState<
    Id<"households"> | ""
  >("");

  const [isFinalising, setIsFinalising] = useState(false);
  const [includedMemberIds, setIncludedMemberIds] = useState<Set<Id<"users">>>(
    new Set(),
  );
  const [hasTouchedMemberSelection, setHasTouchedMemberSelection] =
    useState(false);
  const memberSeedHouseholdRef = useRef<Id<"households"> | null>(null);
  const lastGenerationMemberIdsRef = useRef<Set<Id<"users">>>(new Set());
  const [pickerState, setPickerState] = useState<{
    mode: "add" | "replace";
    entry?: CurrentPlan["entries"][number];
  } | null>(null);
  const [mealPlanLeftoverIds, setMealPlanLeftoverIds] = useState<
    Id<"ingredients">[]
  >([]);
  const [mealPlanLeftoverPhrases, setMealPlanLeftoverPhrases] = useState<
    string[]
  >([]);
  const [generationFallbackStage, setGenerationFallbackStage] =
    useState<GenerationFallbackStage | null>(null);
  const {
    entitlementsReady,
    canUseMealPlanLeftovers,
    blocksAdditionalPlansOnFreeTier,
    controlsLocked,
  } = resolveMealPlanEntitlements({
    currentUser,
    ownedPlanCountForCreation,
  });

  const [dayOption, setDayOption] = useState<"3" | "5" | "7" | "custom">("7");
  const [customDayCount, setCustomDayCount] = useState(
    String(MAX_DAYS_IN_MEAL_PLAN),
  );
  const [quickMealsPresetId, setQuickMealsPresetId] =
    useState<QuickMealsPresetId>("automatic");
  const [startDateOption, setStartDateOption] = useState<
    "today" | "tomorrow" | "following" | "custom"
  >("today");
  const [customStartDate, setCustomStartDate] = useState("");

  const selectedDayCount = useMemo(() => {
    if (controlsLocked) return MAX_DAYS_IN_MEAL_PLAN;
    if (dayOption === "custom") {
      const parsed = Number.parseInt(customDayCount, 10);
      if (Number.isNaN(parsed)) return MAX_DAYS_IN_MEAL_PLAN;
      return Math.max(1, Math.min(MAX_DAYS_IN_MEAL_PLAN, parsed));
    }
    return Number.parseInt(dayOption, 10);
  }, [controlsLocked, customDayCount, dayOption]);

  const requiresHouseholdSelection = (households?.length ?? 0) > 1;
  const missingRequiredHouseholdSelection =
    requiresHouseholdSelection && generateWeekHouseholdId === "";
  const effectiveGenerationHouseholdId = requiresHouseholdSelection
    ? generateWeekHouseholdId || undefined
    : households?.length === 1
      ? households[0]?._id
      : undefined;
  const generationMembers = useQuery(
    api.households.getGenerationMembersWithPreferences,
    effectiveGenerationHouseholdId
      ? { householdId: effectiveGenerationHouseholdId as Id<"households"> }
      : "skip",
  );

  const selectedStartDate = useMemo(() => {
    const utcStartForLocalDate = (offsetDays: number): number => {
      const local = new Date(localDayStartMs);
      local.setDate(local.getDate() + offsetDays);
      return Date.UTC(local.getFullYear(), local.getMonth(), local.getDate());
    };

    if (controlsLocked) return utcStartForLocalDate(0);
    if (startDateOption === "today") return utcStartForLocalDate(0);
    if (startDateOption === "tomorrow") return utcStartForLocalDate(1);
    if (startDateOption === "following") return utcStartForLocalDate(2);
    if (!customStartDate) return utcStartForLocalDate(0);

    const [year, month, day] = customStartDate.split("-").map(Number);
    if (
      Number.isNaN(year) ||
      Number.isNaN(month) ||
      Number.isNaN(day) ||
      year <= 0 ||
      month <= 0 ||
      day <= 0
    ) {
      return utcStartForLocalDate(0);
    }
    return Date.UTC(year, month - 1, day);
  }, [controlsLocked, customStartDate, localDayStartMs, startDateOption]);

  const followingDayLabel = useMemo(() => {
    const followingDayMs = localDayStartMs + 2 * ONE_DAY_MS;
    return new Date(followingDayMs).toLocaleDateString(undefined, {
      weekday: "short",
      month: "short",
      day: "numeric",
    });
  }, [localDayStartMs]);

  useEffect(() => {
    setHasTouchedMemberSelection(false);
  }, [effectiveGenerationHouseholdId]);

  useEffect(() => {
    if (!effectiveGenerationHouseholdId || !generationMembers) return;
    const currentMemberIds = new Set(
      generationMembers.map((member) => member.userId),
    );
    setIncludedMemberIds((prev) => {
      if (memberSeedHouseholdRef.current !== effectiveGenerationHouseholdId) {
        memberSeedHouseholdRef.current = effectiveGenerationHouseholdId;
        lastGenerationMemberIdsRef.current = currentMemberIds;
        return new Set(currentMemberIds);
      }
      if (!hasTouchedMemberSelection && prev.size === 0) {
        lastGenerationMemberIdsRef.current = currentMemberIds;
        return new Set(currentMemberIds);
      }
      const next = new Set(prev);
      for (const id of currentMemberIds) {
        if (!lastGenerationMemberIdsRef.current.has(id)) {
          next.add(id);
        }
      }
      for (const id of lastGenerationMemberIdsRef.current) {
        if (!currentMemberIds.has(id)) {
          next.delete(id);
        }
      }
      lastGenerationMemberIdsRef.current = currentMemberIds;
      return next;
    });
  }, [
    effectiveGenerationHouseholdId,
    generationMembers,
    hasTouchedMemberSelection,
  ]);

  useEffect(() => {
    const memberDefault = Math.max(
      TARGET_SERVINGS_MIN,
      Math.min(TARGET_SERVINGS_MAX, includedMemberIds.size || 1),
    );
    if (!hasManualServingOverride) {
      setTargetServings(memberDefault);
    }
  }, [includedMemberIds.size, hasManualServingOverride]);

  useEffect(() => {
    if (currentUser === undefined) return;
    if (!canUseMealPlanLeftovers) {
      setMealPlanLeftoverIds([]);
      setMealPlanLeftoverPhrases([]);
      return;
    }
    if (!currentPlan) return;
    setMealPlanLeftoverIds(currentPlan.leftoverIngredientIds ?? []);
    setMealPlanLeftoverPhrases(currentPlan.leftoverIngredientPhrases ?? []);
  }, [currentPlan, canUseMealPlanLeftovers, currentUser]);

  useEffect(() => {
    setGenerationFallbackStage(null);
    if (generationOnly || !currentPlan) return;
    if (typeof window === "undefined") return;

    const raw = sessionStorage.getItem(
      MEAL_PLAN_GENERATION_FALLBACK_NOTICE_SESSION_KEY,
    );
    if (!raw) return;

    try {
      const parsed = JSON.parse(raw) as {
        planId?: string;
        stage?: GenerationFallbackStage;
      };
      if (
        parsed.planId === currentPlan._id &&
        (parsed.stage === "recency_relaxed" ||
          parsed.stage === "non_allergy_relaxed")
      ) {
        setGenerationFallbackStage(parsed.stage);
        sessionStorage.removeItem(MEAL_PLAN_GENERATION_FALLBACK_NOTICE_SESSION_KEY);
      } else if (parsed.planId !== currentPlan._id) {
        setGenerationFallbackStage(null);
      }
    } catch {
      sessionStorage.removeItem(MEAL_PLAN_GENERATION_FALLBACK_NOTICE_SESSION_KEY);
    }
  }, [currentPlan, generationOnly]);

  const entriesSorted = useMemo(() => {
    const entries = currentPlan?.entries ?? [];
    return [...entries].sort(
      (a, b) => (a.order ?? 999) - (b.order ?? 999) || a.date - b.date,
    );
  }, [currentPlan?.entries]);

  const visiblePlanDays = useMemo(() => {
    if (!currentPlan) return selectedDayCount;
    if (currentPlan.startDate !== undefined) {
      const computedDays =
        Math.floor((currentPlan.endDate - currentPlan.startDate) / ONE_DAY_MS) +
        1;
      return Math.max(1, computedDays);
    }
    return selectedDayCount;
  }, [currentPlan, selectedDayCount]);

  const emptySlotsCount = useMemo(() => {
    const entryCount = currentPlan?.entries?.length ?? 0;
    const draftPlanDayCount = currentPlan
      ? ((currentPlan as { dayCount?: number }).dayCount ??
        visiblePlanDays)
      : 7;
    const displaySlotTarget = currentPlan?.isFinalised
      ? visiblePlanDays
      : Math.max(1, draftPlanDayCount);
    return Math.max(0, displaySlotTarget - entryCount);
  }, [currentPlan, visiblePlanDays]);

  const handleGenerateWeek = useCallback(async () => {
    if (blocksAdditionalPlansOnFreeTier) {
      toast.error(
        "Free users can only have one active meal plan at a time. Delete your existing plan or upgrade to create another.",
      );
      return;
    }
    if (households === undefined) {
      toast.info("Loading households…");
      return;
    }
    if (requiresHouseholdSelection && generateWeekHouseholdId === "") {
      toast.info("Select a household before generating your plan.");
      return;
    }
    if (
      effectiveGenerationHouseholdId &&
      canUseMealPlanLeftovers &&
      generationMembers === undefined
    ) {
      toast.info("Loading household members, please wait.");
      return;
    }
    if (
      canUseMealPlanLeftovers &&
      generationMembers &&
      generationMembers.length > 0 &&
      includedMemberIds.size === 0
    ) {
      toast.info("Select at least one household member.");
      return;
    }
    trackEvent(ANALYTICS_EVENTS.ONBOARDING_GENERATE_WEEK_CLICKED, {
      surface: "meal_plan",
    });
    setIsGenerating(true);
    try {
      const payload: {
        householdId?: Id<"households">;
        leftoverIngredientIds?: Id<"ingredients">[];
        leftoverIngredientPhrases?: string[];
        startDate?: number;
        dayCount?: number;
        includedMemberUserIds?: Id<"users">[];
        targetServings?: number;
        quickMealsCount?: number;
        quickMealsMaxMinutes?: number;
      } = {};
      if (effectiveGenerationHouseholdId) {
        payload.householdId =
          effectiveGenerationHouseholdId as Id<"households">;
      }
      payload.startDate = selectedStartDate;
      payload.dayCount = selectedDayCount;
      if (
        canUseMealPlanLeftovers &&
        (mealPlanLeftoverIds.length > 0 || mealPlanLeftoverPhrases.length > 0)
      ) {
        if (mealPlanLeftoverIds.length > 0) {
          payload.leftoverIngredientIds = mealPlanLeftoverIds;
        }
        if (mealPlanLeftoverPhrases.length > 0) {
          payload.leftoverIngredientPhrases = mealPlanLeftoverPhrases;
        }
      }
      if (
        canUseMealPlanLeftovers &&
        generationMembers &&
        generationMembers.length > 0
      ) {
        payload.includedMemberUserIds = Array.from(includedMemberIds);
      }
      payload.targetServings = Math.max(
        TARGET_SERVINGS_MIN,
        Math.min(TARGET_SERVINGS_MAX, targetServings),
      );
      if (canUseMealPlanLeftovers) {
        const quickFields = resolveQuickMealsPayloadFields(
          quickMealsPresetId,
          selectedDayCount,
        );
        if (quickFields) {
          if (quickFields.quickMealsMaxMinutes < QUICK_MEALS_MIN_MINUTES) {
            toast.error(
              `Quick meals max minutes must be at least ${QUICK_MEALS_MIN_MINUTES}.`,
            );
            setIsGenerating(false);
            return;
          }
          payload.quickMealsCount = quickFields.quickMealsCount;
          payload.quickMealsMaxMinutes = quickFields.quickMealsMaxMinutes;
        }
      }
      const result = await generateWeeklyPlan(payload);
      const { planId } = result;
      let fallbackStage: GenerationFallbackStage | null = null;
      if (
        "generationFallback" in result &&
        result.generationFallback &&
        (result.generationFallback.stage === "recency_relaxed" ||
          result.generationFallback.stage === "non_allergy_relaxed")
      ) {
        fallbackStage = result.generationFallback.stage;
      }
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_GENERATED, {
        shared_with_household: households.length > 1,
      });
      if (typeof window !== "undefined") {
        sessionStorage.setItem(MEAL_PLAN_LAST_VIEWED_STORAGE_KEY, planId);
        if (fallbackStage) {
          const message = generationFallbackMessage(fallbackStage);
          sessionStorage.setItem(
            MEAL_PLAN_GENERATION_FALLBACK_NOTICE_SESSION_KEY,
            JSON.stringify({ planId, stage: fallbackStage }),
          );
          toast.message(message.toast);
        }
      }
      router.push(ROUTES.mealPlanWithId(planId));
      toast.success("Your week is ready!");
      if (
        "leftoverMatchSummary" in result &&
        result.leftoverMatchSummary &&
        !result.leftoverMatchSummary.hasAnyMatch
      ) {
        toast.message(
          "No recipes in your planner pool used those ingredients—we still built a balanced week.",
        );
      }
    } catch (e) {
      const msg = mealPlanErrorMessage(e) || "Failed to generate plan";
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_GENERATE_FAILED, {
        error_reason: mealPlanGenerateFailureReason(e),
      });
      const emptyPool = /no recipes available/i.test(msg);
      toast.error(msg, {
        ...(emptyPool
          ? {
              action: {
                label: "Browse Discover",
                onClick: () => router.push(ROUTES.MY_RECIPES_DISCOVER_TAB),
              },
            }
          : {}),
      });
    } finally {
      setIsGenerating(false);
    }
  }, [
    canUseMealPlanLeftovers,
    generateWeeklyPlan,
    generateWeekHouseholdId,
    households,
    mealPlanLeftoverIds,
    mealPlanLeftoverPhrases,
    generationMembers,
    includedMemberIds,
    effectiveGenerationHouseholdId,
    router,
    selectedDayCount,
    selectedStartDate,
    blocksAdditionalPlansOnFreeTier,
    requiresHouseholdSelection,
    quickMealsPresetId,
    targetServings,
  ]);

  const handleBlankWeek = useCallback(async () => {
    if (blocksAdditionalPlansOnFreeTier) {
      toast.error(
        "Free users can only have one active meal plan at a time. Delete your existing plan or upgrade to create another.",
      );
      return;
    }
    if (households === undefined) {
      toast.info("Loading households…");
      return;
    }
    if (requiresHouseholdSelection && generateWeekHouseholdId === "") {
      toast.info("Select a household before creating a manual plan.");
      return;
    }
    setIsGenerating(true);
    try {
      const payload = requiresHouseholdSelection
        ? {
            householdId: generateWeekHouseholdId as Id<"households">,
          }
        : {};
      const { planId } = await createBlankWeeklyPlan({
        ...payload,
        startDate: selectedStartDate,
        dayCount: selectedDayCount,
        targetServings: Math.max(
          TARGET_SERVINGS_MIN,
          Math.min(TARGET_SERVINGS_MAX, targetServings),
        ),
      });
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_BLANK_CREATED, {
        shared_with_household: households.length > 1,
      });
      if (typeof window !== "undefined") {
        sessionStorage.setItem(MEAL_PLAN_LAST_VIEWED_STORAGE_KEY, planId);
      }
      router.push(ROUTES.mealPlanWithId(planId));
      toast.success("Manual plan ready. Add your meals.");
    } catch (e) {
      toast.error(mealPlanErrorMessage(e) || "Failed to create manual plan");
    } finally {
      setIsGenerating(false);
    }
  }, [
    createBlankWeeklyPlan,
    generateWeekHouseholdId,
    households,
    router,
    selectedDayCount,
    selectedStartDate,
    blocksAdditionalPlansOnFreeTier,
    requiresHouseholdSelection,
    targetServings,
  ]);

  const handleRegenerateWeek = useCallback(async () => {
    if (!currentPlan) return;
    setIsGenerating(true);
    try {
      const result = await regenerateWeeklyPlan({
        previousPlanId: currentPlan._id,
        targetServings:
          currentPlan.targetServings !== undefined
            ? Math.max(
                TARGET_SERVINGS_MIN,
                Math.min(TARGET_SERVINGS_MAX, currentPlan.targetServings),
              )
            : undefined,
        ...(canUseMealPlanLeftovers &&
        (mealPlanLeftoverIds.length > 0 || mealPlanLeftoverPhrases.length > 0)
          ? {
              ...(mealPlanLeftoverIds.length > 0
                ? { leftoverIngredientIds: mealPlanLeftoverIds }
                : {}),
              ...(mealPlanLeftoverPhrases.length > 0
                ? { leftoverIngredientPhrases: mealPlanLeftoverPhrases }
                : {}),
            }
          : {}),
      });
      const { planId } = result;
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_REGENERATED);
      if (typeof window !== "undefined") {
        sessionStorage.setItem(MEAL_PLAN_LAST_VIEWED_STORAGE_KEY, planId);
      }
      router.push(ROUTES.mealPlanWithId(planId));
      toast.success("Week regenerated. Locked meals kept.");
      if (
        "leftoverMatchSummary" in result &&
        result.leftoverMatchSummary &&
        !result.leftoverMatchSummary.hasAnyMatch
      ) {
        toast.message(
          "No recipes in your planner pool used those ingredients. The rest of the week was filled as usual.",
        );
      }
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to regenerate");
    } finally {
      setIsGenerating(false);
    }
  }, [
    canUseMealPlanLeftovers,
    currentPlan,
    mealPlanLeftoverIds,
    mealPlanLeftoverPhrases,
    regenerateWeeklyPlan,
    router,
  ]);

  const handleLockToggle = useCallback(
    async (entry: CurrentPlan["entries"][number]) => {
      try {
        await updateEntry({
          entryId: entry._id,
          isLocked: !entry.isLocked,
        });
        toast.success(entry.isLocked ? "Meal unlocked" : "Meal locked");
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to update");
      }
    },
    [updateEntry],
  );

  const handleSwitchClick = useCallback(
    async (entry: CurrentPlan["entries"][number]) => {
      const pool = poolRecipes ?? [];
      const inPlanIds = new Set(
        (currentPlan?.entries ?? []).map((e) => e.recipeId),
      );
      let candidates = pool.filter(
        (r) => r._id !== entry.recipeId && !inPlanIds.has(r._id),
      );
      if (candidates.length === 0) {
        candidates = pool.filter((r) => r._id !== entry.recipeId);
      }
      if (candidates.length === 0) {
        toast.error("No other recipes available");
        return;
      }
      const picked = candidates[Math.floor(Math.random() * candidates.length)];
      try {
        await updateEntry({ entryId: entry._id, recipeId: picked._id });
        toast.success("Meal changed");
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to change meal");
      }
    },
    [poolRecipes, currentPlan?.entries, updateEntry],
  );

  const handleRemoveEntry = useCallback(
    async (entryId: Id<"mealPlanEntries">) => {
      try {
        await removeEntry({ entryId });
        toast.success("Meal removed");
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to remove meal");
      }
    },
    [removeEntry],
  );

  const handleGenerateList = useCallback(async () => {
    if (!currentPlan) return;
    try {
      const { listId } = await createShoppingListFromMealPlan({
        mealPlanId: currentPlan._id,
        chalkboardItemIds: Array.from(selectedChalkboardIds),
        targetServings: currentPlan.targetServings,
      });
      trackEvent(ANALYTICS_EVENTS.SHOPPING_LIST_GENERATED, {
        meal_count: currentPlan.entries?.length ?? 0,
        chalkboard_items_included: selectedChalkboardIds.size,
      });
      setShowGenerateDialog(false);
      setSelectedChalkboardIds(new Set());
      toast.success("Shopping list created from meal plan");
      router.push(ROUTES.shoppingListWithId(listId));
    } catch (e) {
      toast.error(
        e instanceof Error ? e.message : "Failed to create shopping list",
      );
    }
  }, [
    currentPlan,
    selectedChalkboardIds,
    createShoppingListFromMealPlan,
    router,
  ]);

  const performShareWithHousehold = useCallback(
    async (
      mealPlanId: Id<"mealPlans">,
      householdId: Id<"households">,
      mealCount: number,
    ): Promise<void> => {
      await shareMealPlanWithHousehold({ mealPlanId, householdId });
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_SHARED_WITH_HOUSEHOLD, {
        household_id: householdId,
        meal_count: mealCount,
      });
      setShowShareDialog(false);
      setShareHouseholdId("");
      toast.success("Meal plan shared with household");
    },
    [shareMealPlanWithHousehold],
  );

  const runMealPlanShare = useCallback(
    async (householdId: Id<"households">) => {
      if (!currentPlan || isSharing || shareInFlightRef.current) return;
      shareInFlightRef.current = true;
      setIsSharing(true);
      try {
        await performShareWithHousehold(
          currentPlan._id,
          householdId,
          currentPlan.entries?.length ?? 0,
        );
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to share");
      } finally {
        shareInFlightRef.current = false;
        setIsSharing(false);
      }
    },
    [currentPlan, isSharing, performShareWithHousehold],
  );

  const handleShare = useCallback(async () => {
    if (!shareHouseholdId) return;
    await runMealPlanShare(shareHouseholdId);
  }, [shareHouseholdId, runMealPlanShare]);

  const handleUnshare = useCallback(async () => {
    if (!currentPlan) return;
    try {
      await unshareMealPlan({ mealPlanId: currentPlan._id });
      setShowUnshareConfirmDialog(false);
      toast.success("Meal plan is private again");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to unshare");
    }
  }, [currentPlan, unshareMealPlan]);

  const handleDeletePlan = useCallback(async () => {
    if (!currentPlan) return;
    try {
      await deleteMealPlan({ mealPlanId: currentPlan._id });
      setShowDeletePlanDialog(false);
      toast.success("Meal plan deleted");
      router.replace(ROUTES.MEAL_PLAN, { scroll: false });
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete plan");
    }
  }, [currentPlan, deleteMealPlan, router]);

  const handleFinalisePlan = useCallback(async () => {
    if (!currentPlan) return;
    setIsFinalising(true);
    try {
      await finaliseMealPlan({ mealPlanId: currentPlan._id });
      trackEvent(ANALYTICS_EVENTS.MEAL_PLAN_FINALISED, {
        meal_count: currentPlan.entries?.length ?? 0,
      });
      setShowFinaliseDialog(false);
      toast.success("Plan saved. You can still move meals between days.");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to save plan");
    } finally {
      setIsFinalising(false);
    }
  }, [currentPlan, finaliseMealPlan]);

  const handleMoveEntryToDay = useCallback(
    async (entryId: Id<"mealPlanEntries">, date: number, order: number) => {
      try {
        await updateEntry({ entryId, date, order });
        toast.success("Meal moved");
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to move meal");
      }
    },
    [updateEntry],
  );

  const handlePickerSelect = useCallback(
    async (recipeId: Id<"recipes">) => {
      if (!currentPlan || !pickerState) return;
      try {
        if (pickerState.mode === "add") {
          const date = currentPlan.startDate ?? currentPlan.endDate;
          await addEntry({
            mealPlanId: currentPlan._id,
            date,
            recipeId,
            order: currentPlan.entries?.length ?? 0,
          });
          toast.success("Meal added");
        } else if (pickerState.entry) {
          await updateEntry({
            entryId: pickerState.entry._id,
            recipeId,
          });
          toast.success("Meal changed");
        }
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to update meal");
      } finally {
        setPickerState(null);
      }
    },
    [currentPlan, pickerState, addEntry, updateEntry],
  );

  const chalkboardItemsForGenerate = useMemo(() => {
    const personal = personalChalkboard ?? [];
    const byHousehold = householdChalkboards ?? {};
    const list: { id: Id<"chalkboardItems">; text: string; source: string }[] =
      [];
    personal.forEach((item) => {
      list.push({ id: item._id, text: item.text, source: "Personal" });
    });
    Object.entries(byHousehold).forEach(([householdId, items]) => {
      const householdName =
        households?.find((h) => h._id === householdId)?.name ?? "Household";
      items.forEach((item: { _id: Id<"chalkboardItems">; text: string }) => {
        list.push({ id: item._id, text: item.text, source: householdName });
      });
    });
    return list;
  }, [personalChalkboard, householdChalkboards, households]);

  useEffect(() => {
    if (generationOnly) return;
    if (!resolvedPlanId || currentPlan === undefined) return;
    if (currentPlan === null && planParam) {
      router.replace(ROUTES.MEAL_PLAN, { scroll: false });
    }
  }, [generationOnly, resolvedPlanId, currentPlan, router, planParam]);

  const isPlanListLoading =
    planSummaries === undefined ||
    (!generationOnly && resolvedPlanId === undefined);
  const isPlanDetailLoading =
    !generationOnly &&
    resolvedPlanId !== null &&
    resolvedPlanId !== undefined &&
    currentPlan === undefined;

  if (isPlanListLoading || isPlanDetailLoading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Skeleton className="h-10 w-64 mb-4" />
        <Skeleton className="h-32 w-full mb-4" />
        <Skeleton className="h-48 w-full" />
      </div>
    );
  }

  if (generationOnly) {
    return (
      <div className="bg-background w-full min-w-0 overflow-x-hidden">
        <div className="container mx-auto px-4 py-8">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8">
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-2">
                Your Weekly Plan
              </h1>
              <p className="text-muted-foreground text-base sm:text-lg">
                Pick your timing, then generate a dedicated meal plan page.
              </p>
            </div>
          </div>
          {planSummaries.length > 0 ? (
            <Card className="mb-6 max-w-2xl mx-auto">
              <CardContent className="p-5 space-y-3">
                <h2 className="font-semibold text-lg">Your Meal Plans</h2>
                <div className="space-y-2">
                  {planSummaries.map((summary) => (
                    <Button
                      key={summary._id}
                      variant="outline"
                      className="w-full justify-between"
                      onClick={() =>
                        router.push(ROUTES.mealPlanWithId(summary._id))
                      }
                    >
                      <span>
                        {formatPlanRangeShort(
                          summary.startDate,
                          summary.endDate,
                        )}
                      </span>
                      <span className="text-muted-foreground">
                        {summary.isFinalised ? "Saved" : "Draft"}
                      </span>
                    </Button>
                  ))}
                </div>
              </CardContent>
            </Card>
          ) : null}
          <Card className="mb-6 border-border/80 bg-muted/20 max-w-2xl mx-auto">
            <CardContent className="p-3 space-y-3">
              <MealPlanProSectionHeader
                icon={
                  <SlidersHorizontal
                    className="size-4 shrink-0 text-primary"
                    aria-hidden
                  />
                }
                title="Meal plan controls"
              />
              {controlsLocked ? (
                <PremiumFeatureNotice
                  title="Pro feature"
                  description="You can preview these options now."
                />
              ) : null}
              <div className="space-y-2">
                <p className="text-sm font-medium text-foreground">Days</p>
                <div
                  role="radiogroup"
                  aria-label="Meal plan day options"
                  className="grid grid-cols-2 sm:grid-cols-4 gap-2"
                >
                  {(["3", "5", "7", "custom"] as const).map((option) => (
                    <label
                      key={option}
                      className={cn(
                        "rounded-lg border px-3 py-3 text-left text-sm transition-colors cursor-pointer focus-within:ring-2 focus-within:ring-primary/50 focus-within:ring-offset-2",
                        dayOption === option
                          ? "border-primary bg-primary/10 text-foreground"
                          : "border-border bg-card text-muted-foreground",
                        controlsLocked && "cursor-not-allowed opacity-60",
                      )}
                    >
                      <input
                        type="radio"
                        name="day-option"
                        value={option}
                        checked={dayOption === option}
                        onChange={() => setDayOption(option)}
                        disabled={controlsLocked}
                        className="peer sr-only"
                      />
                      {option === "custom" ? "Custom" : `${option} days`}
                    </label>
                  ))}
                </div>
                {dayOption === "custom" ? (
                  <div className="max-w-40">
                    <Label htmlFor="custom-day-count" className="text-xs">
                      {`Custom days (max ${MAX_DAYS_IN_MEAL_PLAN})`}
                    </Label>
                    <input
                      id="custom-day-count"
                      type="number"
                      min={1}
                      max={MAX_DAYS_IN_MEAL_PLAN}
                      placeholder={`1-${MAX_DAYS_IN_MEAL_PLAN}`}
                      value={customDayCount}
                      onChange={(e) => setCustomDayCount(e.target.value)}
                      disabled={controlsLocked}
                      className="mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm"
                    />
                  </div>
                ) : null}
              </div>
              <div className="space-y-2">
                <p className="text-sm font-medium text-foreground">Starts</p>
                <div
                  role="radiogroup"
                  aria-label="Meal plan start date options"
                  className="grid grid-cols-2 sm:grid-cols-4 gap-2"
                >
                  {(
                    [
                      ["today", "Today"],
                      ["tomorrow", "Tomorrow"],
                      ["following", followingDayLabel],
                      ["custom", "Custom date"],
                    ] as const
                  ).map(([option, label]) => (
                    <label
                      key={option}
                      className={cn(
                        "rounded-lg border px-3 py-3 text-left text-sm transition-colors cursor-pointer focus-within:ring-2 focus-within:ring-primary/50 focus-within:ring-offset-2",
                        startDateOption === option
                          ? "border-primary bg-primary/10 text-foreground"
                          : "border-border bg-card text-muted-foreground",
                        controlsLocked && "cursor-not-allowed opacity-60",
                      )}
                    >
                      <input
                        type="radio"
                        name="start-date-option"
                        value={option}
                        checked={startDateOption === option}
                        onChange={() => setStartDateOption(option)}
                        disabled={controlsLocked}
                        className="peer sr-only"
                      />
                      {label}
                    </label>
                  ))}
                </div>
                {startDateOption === "custom" ? (
                  <div className="max-w-56">
                    <Label htmlFor="custom-start-date" className="text-xs">
                      Custom start date
                    </Label>
                    <input
                      id="custom-start-date"
                      type="date"
                      title="Custom start date"
                      value={customStartDate}
                      onChange={(e) => setCustomStartDate(e.target.value)}
                      disabled={controlsLocked}
                      className="mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm"
                    />
                  </div>
                ) : null}
              </div>
            </CardContent>
          </Card>
          <QuickMealsPreferenceCard
            selectedPresetId={quickMealsPresetId}
            onSelectPreset={setQuickMealsPresetId}
            isPremiumEnabled={canUseMealPlanLeftovers}
            selectedDayCount={selectedDayCount}
          />
          <div className="max-w-2xl mx-auto mb-6 w-full">
            <LeftoverIngredientsPicker
              selectedIds={mealPlanLeftoverIds}
              selectedPhrases={mealPlanLeftoverPhrases}
              onSelectionChange={({ ingredientIds, phrases }) => {
                setMealPlanLeftoverIds(ingredientIds);
                setMealPlanLeftoverPhrases(phrases);
              }}
              canUseFeatures={canUseMealPlanLeftovers}
              description="Optional: prioritise recipes that use ingredients you want to finish this week."
            />
          </div>
          <Card className="mb-6 border-border/80 bg-muted/20 max-w-2xl mx-auto">
            <CardContent className="p-3">
              <div className="rounded-lg border border-border p-3">
                <Label
                  htmlFor="target-servings"
                  className="text-sm font-medium"
                >
                  Servings for this plan
                </Label>
                <div className="mt-2 flex items-center gap-2">
                  <Button
                    type="button"
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      setHasManualServingOverride(true);
                      setTargetServings((prev) =>
                        Math.max(TARGET_SERVINGS_MIN, prev - 1),
                      );
                    }}
                  >
                    -
                  </Button>
                  <input
                    id="target-servings"
                    type="number"
                    title="Plan servings"
                    placeholder="Servings"
                    min={TARGET_SERVINGS_MIN}
                    max={TARGET_SERVINGS_MAX}
                    value={targetServings}
                    onChange={(e) => {
                      setHasManualServingOverride(true);
                      const n = Number(e.target.value);
                      if (!Number.isFinite(n)) return;
                      setTargetServings(
                        Math.max(
                          TARGET_SERVINGS_MIN,
                          Math.min(TARGET_SERVINGS_MAX, Math.round(n)),
                        ),
                      );
                    }}
                    className="w-20 rounded-md border bg-background px-3 py-2 text-sm"
                  />
                  <Button
                    type="button"
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      setHasManualServingOverride(true);
                      setTargetServings((prev) =>
                        Math.min(TARGET_SERVINGS_MAX, prev + 1),
                      );
                    }}
                  >
                    +
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => setHasManualServingOverride(false)}
                  >
                    Reset
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
          {effectiveGenerationHouseholdId &&
          generationMembers &&
          generationMembers.length > 0 ? (
            <Card className="mb-6 border-border/80 bg-muted/20 max-w-2xl mx-auto">
              <CardContent className="p-3 space-y-3">
                <MealPlanProSectionHeader
                  icon={
                    <UserRoundCheck
                      className="size-4 shrink-0 text-primary"
                      aria-hidden
                    />
                  }
                  title="Include member preferences"
                />
                <p className="text-sm text-muted-foreground">
                  Tap to exclude members from this plan. For anyone still
                  included, we won&apos;t suggest recipes that use their listed{" "}
                  <Link
                    href="/dashboard/preferences"
                    className="text-primary underline"
                  >
                    preferences and allergens
                  </Link>
                  .
                </p>
                {canUseMealPlanLeftovers ? (
                  <>
                    <MemberPreferenceCards
                      members={generationMembers}
                      includedMemberIds={includedMemberIds}
                      onToggle={(userId) => {
                        setHasTouchedMemberSelection(true);
                        setIncludedMemberIds((prev) => {
                          const next = new Set(prev);
                          if (next.has(userId)) next.delete(userId);
                          else next.add(userId);
                          return next;
                        });
                      }}
                    />
                  </>
                ) : (
                  <PremiumFeatureNotice
                    title="Pro feature"
                    description="Member preference filtering is available on Pro."
                  />
                )}
                {canUseMealPlanLeftovers && includedMemberIds.size === 0 ? (
                  <p className="text-xs text-destructive">
                    Select at least one member to generate a plan.
                  </p>
                ) : null}
              </CardContent>
            </Card>
          ) : null}
          <Card className="border-2 border-dashed border-muted-foreground/25 bg-card p-8 sm:p-10 text-center max-w-xl mx-auto">
            <CardContent className="p-0 flex flex-col items-center">
              <div className="size-16 rounded-full border-2 border-primary/30 bg-primary/10 flex items-center justify-center mb-6">
                <Sparkles className="size-8 text-primary" />
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-foreground mb-2">
                Ready to eat better?
              </h2>
              <p className="text-muted-foreground mb-3 max-w-sm mx-auto">
                We pick from the curated catalog plus your library so you get a
                full week in seconds.
              </p>
              <p className="text-muted-foreground text-sm mb-6 max-w-sm mx-auto">
                Prefer to pick every meal yourself? Start a manual plan with
                empty days, then fill them in.
              </p>
              {households && households.length > 1 ? (
                <div className="mb-4 w-full max-w-sm text-left space-y-1.5">
                  <Label htmlFor="empty-gen-household">Household</Label>
                  <Select
                    value={generateWeekHouseholdId}
                    onValueChange={(v) =>
                      setGenerateWeekHouseholdId(v as Id<"households">)
                    }
                  >
                    <SelectTrigger id="empty-gen-household">
                      <SelectValue placeholder="Select household" />
                    </SelectTrigger>
                    <SelectContent>
                      {households.map((h) => (
                        <SelectItem key={h._id} value={h._id}>
                          {h.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              ) : null}
              <GenerationActionButtons
                isGenerating={isGenerating}
                disabledManual={
                  isGenerating ||
                  households === undefined ||
                  missingRequiredHouseholdSelection ||
                  blocksAdditionalPlansOnFreeTier ||
                  !entitlementsReady
                }
                disabledGenerate={
                  isGenerating ||
                  households === undefined ||
                  missingRequiredHouseholdSelection ||
                  (canUseMealPlanLeftovers &&
                    effectiveGenerationHouseholdId &&
                    generationMembers === undefined) ||
                  (canUseMealPlanLeftovers &&
                    (generationMembers?.length ?? 0) > 0 &&
                    includedMemberIds.size === 0) ||
                  blocksAdditionalPlansOnFreeTier ||
                  !entitlementsReady
                }
                onManual={handleBlankWeek}
                onGenerate={handleGenerateWeek}
                showUpgradeHint={blocksAdditionalPlansOnFreeTier}
              />
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  if (planSummaries.length === 0 && resolvedPlanId === null) {
    return (
      <div className="bg-background w-full min-w-0 overflow-x-hidden">
        <div className="container mx-auto px-4 py-8">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8">
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-2">
                Your Weekly Plan
              </h1>
              <p className="text-muted-foreground text-base sm:text-lg">
                One click fills the week from our catalog and recipes
                you&apos;ve saved—then tweak or shop from there.
              </p>
            </div>
          </div>
          <div className="max-w-2xl mx-auto mb-6 w-full">
            <LeftoverIngredientsPicker
              selectedIds={mealPlanLeftoverIds}
              selectedPhrases={mealPlanLeftoverPhrases}
              onSelectionChange={({ ingredientIds, phrases }) => {
                setMealPlanLeftoverIds(ingredientIds);
                setMealPlanLeftoverPhrases(phrases);
              }}
              canUseFeatures={canUseMealPlanLeftovers}
              description="Optional: prioritise recipes that use ingredients you want to finish this week."
            />
          </div>
          <QuickMealsPreferenceCard
            selectedPresetId={quickMealsPresetId}
            onSelectPreset={setQuickMealsPresetId}
            isPremiumEnabled={canUseMealPlanLeftovers}
            selectedDayCount={selectedDayCount}
          />
          {households && households.length > 1 ? (
            <div className="mb-4 w-full max-w-sm text-left space-y-1.5 mx-auto">
              <Label htmlFor="empty-gen-household">Household</Label>
              <Select
                value={generateWeekHouseholdId}
                onValueChange={(v) =>
                  setGenerateWeekHouseholdId(v as Id<"households">)
                }
              >
                <SelectTrigger id="empty-gen-household">
                  <SelectValue placeholder="Select household" />
                </SelectTrigger>
                <SelectContent>
                  {households.map((h) => (
                    <SelectItem key={h._id} value={h._id}>
                      {h.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          ) : null}
          <Card className="border-2 border-dashed border-muted-foreground/25 bg-card p-8 sm:p-10 text-center max-w-xl mx-auto">
            <CardContent className="p-0 flex flex-col items-center">
              <div className="size-16 rounded-full border-2 border-primary/30 bg-primary/10 flex items-center justify-center mb-6">
                <Sparkles className="size-8 text-primary" />
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-foreground mb-2">
                Ready to eat better?
              </h2>
              <p className="text-muted-foreground mb-3 max-w-sm mx-auto">
                We pick from the curated catalog plus your library so you get a
                full week in seconds.
              </p>
              <p className="text-muted-foreground text-sm mb-6 max-w-sm mx-auto">
                Prefer to pick every meal yourself? Start a manual plan with
                empty days, then fill them in.
              </p>
              <GenerationActionButtons
                isGenerating={isGenerating}
                disabledManual={
                  isGenerating ||
                  households === undefined ||
                  missingRequiredHouseholdSelection ||
                  blocksAdditionalPlansOnFreeTier ||
                  !entitlementsReady
                }
                disabledGenerate={
                  isGenerating ||
                  households === undefined ||
                  missingRequiredHouseholdSelection ||
                  (canUseMealPlanLeftovers &&
                    effectiveGenerationHouseholdId &&
                    generationMembers === undefined) ||
                  (canUseMealPlanLeftovers &&
                    (generationMembers?.length ?? 0) > 0 &&
                    includedMemberIds.size === 0) ||
                  blocksAdditionalPlansOnFreeTier ||
                  !entitlementsReady
                }
                onManual={handleBlankWeek}
                onGenerate={handleGenerateWeek}
                showUpgradeHint={blocksAdditionalPlansOnFreeTier}
              />
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  // Defensive: loading guards above usually prevent this; Convex can still return null for a stale ?plan= id before redirect runs.
  if (currentPlan === null || currentPlan === undefined) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Skeleton className="h-10 w-64 mb-4" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }

  const mealCount = currentPlan.entries?.length ?? 0;
  const sharedHousehold = currentPlan.householdId
    ? households?.find((h) => h._id === currentPlan.householdId)
    : null;
  const hasList = listsForPlan && listsForPlan.length > 0;
  const firstListId = listsForPlan?.[0]?._id;

  const isFinalised = currentPlan.isFinalised === true;

  return (
    <div className="bg-background min-w-0 w-full overflow-x-hidden">
      {!isFinalised && currentPlan.isOwner ? <SuppressAppFeedback /> : null}
      <div
        className={cn(
          "relative w-full max-w-full min-w-0 px-4 pt-6 sm:pt-8 sm:container sm:mx-auto box-border",
          !isFinalised && "pb-40",
        )}
      >
        <div className="mb-4">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => navigateBackOr(router, ROUTES.MEAL_PLAN)}
            aria-label="Go back to meal plan generation"
          >
            <ArrowLeft className="size-4" />
            Back
          </Button>
        </div>
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4 sm:mb-6 min-w-0">
          <div className="min-w-0 overflow-hidden">
            <h1 className="text-2xl sm:text-4xl font-bold text-foreground mb-2 truncate">
              Your Weekly Plan
            </h1>
            <p className="text-muted-foreground text-sm sm:text-base truncate">
              {isFinalised
                ? "Drag meals to change which day they fall on."
                : "Review your week. Lock what you love, swap what you don't."}
            </p>
            {planSummaries.length > 1 ? (
              <div className="mt-3 max-w-md space-y-1.5">
                <Label
                  htmlFor="meal-plan-picker"
                  className="text-xs text-muted-foreground"
                >
                  Switch plan
                </Label>
                <Select
                  value={currentPlan._id}
                  onValueChange={(id) => {
                    if (typeof window !== "undefined") {
                      sessionStorage.setItem(
                        MEAL_PLAN_LAST_VIEWED_STORAGE_KEY,
                        id,
                      );
                    }
                    router.push(ROUTES.mealPlanWithId(id));
                  }}
                >
                  <SelectTrigger
                    id="meal-plan-picker"
                    size="sm"
                    className="w-full sm:w-72"
                  >
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {planSummaries.map((s) => (
                      <SelectItem key={s._id} value={s._id}>
                        {formatPlanRangeShort(s.startDate, s.endDate)}
                        {s.isFinalised ? " · Saved" : " · Draft"}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            ) : null}
          </div>
          <div className="flex flex-wrap gap-2 items-center min-w-0 shrink-0">
            <Button variant="outline" asChild>
              <Link href={ROUTES.MEAL_PLAN} aria-label="Create a new meal plan">
                <CalendarPlus className="size-4" />
                New plan
              </Link>
            </Button>
            {hasList && firstListId ? (
              <Button variant="outline" asChild>
                <Link href={ROUTES.shoppingListWithId(firstListId)}>
                  <ShoppingCart className="size-4 " />
                  Shopping List
                </Link>
              </Button>
            ) : (
              <Button
                variant="outline"
                onClick={() => setShowGenerateDialog(true)}
                disabled={mealCount === 0}
              >
                <ShoppingCart className="size-4" />
                Shopping List
              </Button>
            )}
            {currentPlan.isOwner && (
              <>
                {sharedHousehold ? (
                  <Button
                    type="button"
                    variant="default"
                    onClick={() => setShowUnshareConfirmDialog(true)}
                    aria-label="Stop sharing this meal plan with your household"
                  >
                    <UserMinus className="size-4 shrink-0" />
                    <span className="max-w-40 truncate sm:max-w-none">
                      Stop sharing
                    </span>
                  </Button>
                ) : (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setShowShareDialog(true)}
                    aria-label="Share this meal plan with a household"
                  >
                    <Users className="size-4 shrink-0" />
                    <span className="max-w-36 truncate sm:max-w-none">
                      Share with household
                    </span>
                  </Button>
                )}
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label="Plan options"
                    >
                      <MoreVertical className="size-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem
                      className="text-destructive focus:text-destructive"
                      onClick={() => setShowDeletePlanDialog(true)}
                    >
                      <Trash2 className="size-4 mr-2" />
                      Delete meal plan
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </>
            )}
          </div>
        </div>

        <AlertDialog
          open={showDeletePlanDialog}
          onOpenChange={setShowDeletePlanDialog}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete meal plan?</AlertDialogTitle>
              <AlertDialogDescription>
                This will permanently delete this meal plan and all meals in it.
                You can create a new plan anytime.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={(e) => {
                  e.preventDefault();
                  void handleDeletePlan();
                }}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              >
                Delete plan
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        <AlertDialog
          open={showUnshareConfirmDialog}
          onOpenChange={setShowUnshareConfirmDialog}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Stop sharing this plan?</AlertDialogTitle>
              <AlertDialogDescription asChild>
                <div className="grid gap-3 text-sm text-muted-foreground">
                  {sharedHousehold ? (
                    <>
                      <p>
                        People in{" "}
                        <strong className="text-foreground">
                          {sharedHousehold.name}
                        </strong>{" "}
                        will no longer see this meal plan. Shopping lists they
                        could only reach through this plan may disappear from
                        their list until you share again.
                      </p>
                      <p>
                        This turns off the same household access you get when a
                        plan is shared automatically after generating a week.
                        You can use{" "}
                        <strong className="text-foreground">
                          Share with household
                        </strong>{" "}
                        later to share again.
                      </p>
                    </>
                  ) : (
                    <p>Household members will no longer see this meal plan.</p>
                  )}
                </div>
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={(e) => {
                  e.preventDefault();
                  void handleUnshare();
                }}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              >
                Stop sharing
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        <AlertDialog
          open={showFinaliseDialog}
          onOpenChange={setShowFinaliseDialog}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Save this plan?</AlertDialogTitle>
              <AlertDialogDescription>
                Once saved, you can&apos;t add, remove, or swap meals, only move
                them between days. To make bigger changes, you&apos;d need to
                delete this plan and create a new one.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={(e) => {
                  e.preventDefault();
                  void handleFinalisePlan();
                }}
                disabled={isFinalising}
              >
                Save plan
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        {sharedHousehold && (
          <Card className="mb-4 py-4 border-primary/25 bg-primary/5">
            <CardContent className="px-3 flex gap-2 items-center">
              <div className="mt-0.5 rounded-md bg-primary/15 p-1.5 shrink-0">
                <Home className="size-4 text-primary" />
              </div>
              <div className="min-w-0 text-sm">
                <p className="font-medium text-foreground leading-none">
                  Shared with{" "}
                  <span className="text-primary">{sharedHousehold.name}</span>
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {generationFallbackStage && (
          <Card className="mb-4 border-amber-400/30 bg-amber-500/10 py-4">
            <CardContent className="flex items-start justify-between gap-3 px-3">
              <p className="text-sm text-foreground/90">
                {generationFallbackMessage(generationFallbackStage).banner}
              </p>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 px-2 text-xs shrink-0"
                onClick={() => setGenerationFallbackStage(null)}
              >
                Dismiss
              </Button>
            </CardContent>
          </Card>
        )}

        {isFinalised ? (
          <MealPlanDayView
            plan={currentPlan}
            onMoveEntry={handleMoveEntryToDay}
          />
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 w-full min-w-0 max-w-full">
            {entriesSorted.map((entry) => {
              const cardEntry =
                entry.recipe == null
                  ? entry
                  : {
                      ...entry,
                      recipe: {
                        ...entry.recipe,
                        category: entry.recipe.category ?? "",
                      },
                    };
              return (
                <MealPlanCard
                  key={entry._id}
                  entry={cardEntry}
                  isOwner={currentPlan.isOwner ?? false}
                  onLockToggle={() => handleLockToggle(entry)}
                  onSwitch={() => handleSwitchClick(entry)}
                  onRemove={() => handleRemoveEntry(entry._id)}
                  onChangeRecipe={
                    currentPlan.isOwner && !isFinalised
                      ? () => setPickerState({ mode: "replace", entry })
                      : undefined
                  }
                />
              );
            })}
            {Array.from({ length: emptySlotsCount }, (_, i) => (
              <EmptySlot
                key={`empty-${i}`}
                onAdd={
                  currentPlan.isOwner && !isFinalised
                    ? () => setPickerState({ mode: "add" })
                    : undefined
                }
              />
            ))}
          </div>
        )}

        <MealPlanRecipePickerModal
          open={pickerState !== null}
          onOpenChange={(open) => {
            if (!open) setPickerState(null);
          }}
          mode={pickerState?.mode ?? "add"}
          replaceEntry={
            pickerState?.mode === "replace" ? pickerState.entry : undefined
          }
          onSelect={handlePickerSelect}
        />

        {/* Generate shopping list dialog */}
        <Dialog open={showGenerateDialog} onOpenChange={setShowGenerateDialog}>
          <DialogContent className="flex max-h-[calc(100dvh-2rem)] flex-col p-0">
            <div className="flex-1 overflow-y-auto px-6 pt-6 space-y-4">
              <DialogHeader>
                <DialogTitle>Generate shopping list</DialogTitle>
                <DialogDescription>
                  Create a shopping list from your meal plan ingredients.
                  Optionally include chalkboard items.
                </DialogDescription>
              </DialogHeader>
              {listsForPlan && listsForPlan.length > 0 && (
                <p className="text-sm text-muted-foreground">
                  You have an existing list for this plan:{" "}
                  <Link
                    href={ROUTES.shoppingListWithId(listsForPlan[0]._id)}
                    className="font-medium text-primary underline underline-offset-4"
                    onClick={() => setShowGenerateDialog(false)}
                  >
                    View list
                  </Link>
                </p>
              )}
              {chalkboardItemsForGenerate.length > 0 && (
                <div className="space-y-2 py-2">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <Label className="shrink-0">Include chalkboard items</Label>
                    <div className="flex flex-wrap gap-2 shrink-0">
                      <Button
                        type="button"
                        variant="secondary"
                        size="sm"
                        onClick={() =>
                          setSelectedChalkboardIds(
                            new Set(
                              chalkboardItemsForGenerate.map((i) => i.id),
                            ),
                          )
                        }
                        disabled={
                          selectedChalkboardIds.size ===
                          chalkboardItemsForGenerate.length
                        }
                      >
                        Add all
                      </Button>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => setSelectedChalkboardIds(new Set())}
                        disabled={selectedChalkboardIds.size === 0}
                      >
                        Clear
                      </Button>
                    </div>
                  </div>
                  <div className="max-h-40 overflow-y-auto space-y-2 border rounded-md p-2">
                    {chalkboardItemsForGenerate.map((item) => (
                      <label
                        key={item.id}
                        className="flex items-center gap-2 cursor-pointer"
                      >
                        <input
                          type="checkbox"
                          checked={selectedChalkboardIds.has(item.id)}
                          onChange={(e) => {
                            setSelectedChalkboardIds((prev) => {
                              const next = new Set(prev);
                              if (e.target.checked) next.add(item.id);
                              else next.delete(item.id);
                              return next;
                            });
                          }}
                        />
                        <span className="text-sm truncate">{item.text}</span>
                        <Badge variant="secondary" className="text-xs shrink-0">
                          {item.source}
                        </Badge>
                      </label>
                    ))}
                  </div>
                </div>
              )}
            </div>
            <DialogFooter className="shrink-0 border-t px-6 py-4">
              <Button
                variant="outline"
                onClick={() => setShowGenerateDialog(false)}
              >
                Cancel
              </Button>
              <Button onClick={handleGenerateList}>Create shopping list</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Share with household dialog */}
        <Dialog open={showShareDialog} onOpenChange={setShowShareDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Share with household</DialogTitle>
              <DialogDescription>
                Use this when your plan is private and you want household
                members to see it. If the plan is already shared, use the{" "}
                <span className="font-medium text-foreground">
                  Stop sharing
                </span>{" "}
                button on the plan (not this dialog) to make it private again.
              </DialogDescription>
            </DialogHeader>
            {households && households.length === 1 ? (
              <div className="py-2">
                <p className="text-sm text-muted-foreground mb-4">
                  Share with <strong>{households[0].name}</strong>
                </p>
                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setShowShareDialog(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    disabled={isSharing}
                    onClick={() => {
                      if (!households[0]) return;
                      void runMealPlanShare(households[0]._id);
                    }}
                  >
                    Share
                  </Button>
                </DialogFooter>
              </div>
            ) : (
              <>
                <div className="py-2">
                  <Label>Household</Label>
                  <Select
                    value={shareHouseholdId}
                    onValueChange={(v) =>
                      setShareHouseholdId(v as Id<"households">)
                    }
                  >
                    <SelectTrigger className="mt-2">
                      <SelectValue placeholder="Select household" />
                    </SelectTrigger>
                    <SelectContent>
                      {(households ?? []).map((h) => (
                        <SelectItem key={h._id} value={h._id}>
                          {h.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setShowShareDialog(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={() => void handleShare()}
                    disabled={!shareHouseholdId || isSharing}
                  >
                    Share
                  </Button>
                </DialogFooter>
              </>
            )}
          </DialogContent>
        </Dialog>

        {!isFinalised && currentPlan.isOwner && (
          <div
            className={cn(
              "fixed bottom-0 inset-x-0 z-40 pointer-events-none",
              "bottom-(--nav-height) px-4 py-3 sm:px-6 sm:py-4",
            )}
          >
            <div className="mx-auto max-w-3xl pointer-events-auto rounded-2xl border border-border/80 bg-background/95 p-3 shadow-[0_-12px_40px_rgba(0,0,0,0.16)] supports-backdrop-filter:bg-background/85 supports-backdrop-filter:backdrop-blur-xl">
              <p className="mb-3 max-w-prose text-xs leading-snug text-foreground/80">
                Save your plan to open recipes from this week. After saving you
                can still move meals between days.
              </p>
              <div className="flex items-stretch justify-between gap-3">
                <Button
                  type="button"
                  variant="outline"
                  size="lg"
                  className="min-h-12 flex-1 shrink"
                  onClick={handleRegenerateWeek}
                  disabled={isGenerating}
                >
                  <Sparkles className="size-5 shrink-0" />
                  Regenerate
                </Button>
                <Button
                  type="button"
                  variant="default"
                  size="lg"
                  className="min-h-12 flex-1 shrink"
                  onClick={() => setShowFinaliseDialog(true)}
                  disabled={mealCount === 0}
                >
                  <CheckCircle2 className="size-5 shrink-0" />
                  Save plan
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
