/**
 * Distinct ingredient food sub-groups currently present in the database / seed.
 *
 * Source: convex/ingredients-seed.json and live ingredient data.
 * Keep in sync when new food sub-groups appear. Run:
 *   npx convex run ingredients:getDistinctFoodSubGroups
 * (after deploying) to verify against live data.
 */

export const INGREDIENT_FOOD_SUB_GROUPS = [
  "Alcoholic beverages",
  "American cuisine",
  "Amphibians",
  "Animal fats",
  "Asian cuisine",
  "Baby foods",
  "Baking goods",
  "Beans",
  "Berber cuisine",
  "Berries",
  "Beverages",
  "Bivalvia",
  "Bovines",
  "Brassicas",
  "Bread products",
  "Cabbages",
  "Candies",
  "Caprae",
  "Cereal products",
  "Cereals",
  "Cereals and cereal products",
  "Cetaceans",
  "Citrus",
  "Cocoa",
  "Cocoa and cocoa products",
  "Cocoa products",
  "Coffee",
  "Coffee and coffee products",
  "Coffee products",
  "Condiments",
  "Crustaceans",
  "Desserts",
  "Distilled beverages",
  "Doughs",
  "Dressings",
  "Drupes",
  "Eggs",
  "Equines",
  "Fats and oils",
  "Fermented beverages",
  "Fermented milk products",
  "Fermented milks",
  "Fish products",
  "Fishes",
  "Flat breads",
  "Fortified wines",
  "Frozen desserts",
  "Fruit products",
  "Fruit vegetables",
  "Fruits",
  "Gourds",
  "Green vegetables",
  "Ground meat",
  "Herb and spice mixtures",
  "Herbal teas",
  "Herbs",
  "Herbs and Spices",
  "Jewish cuisine",
  "Lagomorphs",
  "Latin American cuisine",
  "Leaf vegetables",
  "Leavened breads",
  "Lentils",
  "Levantine cuisine",
  "Mexican cuisine",
  "Milk and milk products",
  "Milk desserts",
  "Mollusks",
  "Mushrooms",
  "Nutritional beverages",
  "Nuts",
  "Oilseed crops",
  "Onion-family vegetables",
  "Other aquatic foods",
  "Other beverages",
  "Other breads",
  "Other confectioneries",
  "Other dishes",
  "Other fruits",
  "Other milk products",
  "Other pulses",
  "Other seeds",
  "Other vegetables",
  "Ovis",
  "Pasta dishes",
  "Peas",
  "Pinnipeds",
  "Pomes",
  "Potato dishes",
  "Poultry",
  "Pulses",
  "Roe",
  "Root vegetables",
  "Sandwiches",
  "Sauces",
  "Seasonings",
  "Seaweed",
  "Sheep",
  "Shoot vegetables",
  "Snack foods",
  "Soy",
  "Soy products",
  "Spices",
  "Spreads",
  "Stalk vegetables",
  "Substitutes",
  "Sugars",
  "Sweet breads",
  "Swine",
  "Teas",
  "Tex-Mex cuisine",
  "Tropical fruits",
  "Tubers",
  "Unclassified",
  "Unfermented milks",
  "Vegetable fats",
  "Vegetable products",
  "Venison",
  "Waters",
  "Wrappers",
] as const;

export type IngredientFoodSubGroup = (typeof INGREDIENT_FOOD_SUB_GROUPS)[number];
